services:
  weather-app:
    build:
      context: .
      args:
        - VITE_APP_ID=${VITE_APP_ID}
    ports:
      - "0.0.0.0:8080:80"
    env_file:
      - .env
    container_name: weather_app-container